#!/bin/bash

# 显示预设workflow信息的脚本

echo ""
echo "🎨 =========================================="
echo "🎨   ComfyUI Docker 预设 Workflow 指南"
echo "🎨 =========================================="
echo ""
echo "📁 预设文件位置："
echo "   • 拖拽图片: /root/input/"
echo "     - flux_dev.png (Flux模型workflow)"
echo "     - sd3.5.png (SD3.5模型workflow)"
echo ""
echo "   • JSON文件: /root/user/default/workflows/"
echo "     - flux_dev.json"
echo "     - sd3.5_text_encoders_example.json"
echo ""
echo "🚀 快速开始："
echo "   1. 打开浏览器访问: http://localhost:8188"
echo "   2. 将PNG图片从input目录拖拽到工作区"
echo "   3. 或使用 Ctrl+O 加载JSON文件"
echo "   4. 修改提示词，点击 'Queue Prompt' 开始生成"
echo ""
echo "📖 详细说明请查看: /root/ComfyUI-Example-Workflows/WORKFLOW_GUIDE.zh.md"
echo ""
echo "🔗 API访问: http://localhost:8188/workflow_templates"
echo ""
echo "🎨 =========================================="
echo ""
